[build]
  publish = "."

[[redirects]]
  from = "/privacy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  from = "/cookies"
  to = "/cookie-policy.html"
  status = 200
